### ISSUE TITLE
[Question] Compatibility with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by jdimmerman** [olirice/alembic_utils#104]
Hi - I saw that you recently pinned to under SQLAlchemy 2.0. Was there an associated set of issues that caused you to do this and any idea if you'll be supporting SQLAlchemy 2+?

Thanks!

**Comment by olirice** [comment]
During a recent update I found that the test suite fails under sqla 2.0. I would like alembic_utils to support it but haven't had the time to dig in. For now the version is pinned to communicate the issue

If anyone would like to contribute, this would be a good PR

**Comment by jdimmerman** [comment]
Thanks @olirice! I've started a PR though there is one failing test and I need to switch my attention to something else. I'll come back to this if no one picks it up.

https://github.com/olirice/alembic_utils/pull/105

**Comment by olirice** [comment]
resolved by #105

**Comment by jdimmerman** [comment]
Thanks!
