### ISSUE TITLE
DropOp dependency ordering when dropping multiple associated entities

### ISSUE THREAD

**Issue by tauseef13bok** [olirice/alembic_utils#117]
I created a trigger and a function on which the trigger operates. then i changed the signature of trigger and function . Now as function depend on trigger , first trigger should be dropped and then function ... But strangely in migration files sometimes first trigger is dropped and then functions and sometimes first function and then triggers which is causing errors when upgrading db.

I have attached three files . In triggers.py file triggers and functions are defined ...pl. just keep changing the signatures of func and trig and re run the migration 3 4 times ..
[Desktop.zip](https://github.com/olirice/alembic_utils/files/12701726/Desktop.zip)

**Comment by tauseef13bok** [comment]
Hi .I created a fork , to solve the dependency ordering . My fork  supports ordering of nested dependencies for both create and drop operation. Could you have a look?

**Comment by olirice** [comment]
If you could open a PR an annotate the changes I'd be happy to take a look!

**Comment by tauseef13bok** [comment]
Sure. done.
