### ISSUE TITLE
Publishing next release

### ISSUE THREAD

**Issue by hewkels** [olirice/alembic_utils#118]
We're using the alembic_utils package to create `PGViews` but found we the latest published version 0.8.1 is missing a patch commit (6d6a6f17f0de90415ecb7dcb13f90146c50f2f6f) we need for our migrations to run properly, meaning we have to point to the latest git commit in our poetry.lock file.

Is there a planned release of a latest version including the latest commits?
Thanks!

**Comment by olirice** [comment]
thanks for the nudge. now available on pypi under 0.8.2
