### ISSUE TITLE
Getting error permission denied on alembic_version when try to migrate.

### ISSUE THREAD

**Issue by singgihmardianto** [olirice/alembic_utils#133]
Hi there, 

I am getting error permission denied on alembic_version table when try to migrate it. The autogeneration work perfectly though.

So first, here is my `customer.py` which I declare the alembic `PGMaterializedView`

![image](https://github.com/user-attachments/assets/0427af3e-f167-40b9-a434-e2b507ac7d2e)

Then this is my `env.py` file, I declare customer.py in other file, and import it as `Entity`

![image](https://github.com/user-attachments/assets/33d2b892-2db8-4324-9966-3ca93abfd2a6)

And the migration file was created perfectly like this one:

![image](https://github.com/user-attachments/assets/812e8e97-0048-4bc6-8bf7-f711b4e11cbb)

Then I try to run the migration, that's where I got the error permission denied. Such a weird thing, bcs the alembic_version is a basic table. I already run other migration file (not with the PGMaterializedView) and it works.

![image](https://github.com/user-attachments/assets/783b678b-9c2d-482c-b68e-eee58bb136fe)

Can someone explain to me the issue?

Thank you

**Comment by olirice** [comment]
This is a permissions issue with stock `alembic` vs related to `alembic_utils`.
check that the `role` in your connection string in `alembic.ini` has sufficient permissions to query the table.

It sounds like you maybe ran an initial migration with a highly privileged role like `postgres` and now are using a lower privileged role.

Grab the role from `alembic.ini` and you can test if it has access via
```sql
select pg_catalog.has_table_privilege('your_role', 'public.alembic_version', 'select')
```

if it returns false, you need to use your superuser role to
```
grant select on public.alembic_utils to <your_role>
```
