### ISSUE TITLE
Grant without defining columns

### ISSUE THREAD

**Issue by Brax94** [olirice/alembic_utils#137]
Hi, 

After trying alembic utils today, i was a bit stumped that i could not grant access to tables without defining the columns. 
This would mean that for each column added in subsequent migration, the PGGrantTable definition would have to be updated for each user with access to the table, which seems a bit counter intuitive.

After all, "GRANT SELECT on COLUMN for USER1" is a valid statement, at least in postgresql. 

In my case, nothing breaks if changing the code to allow None to be given as the column argument. 
I'd be happy to write a pull request if you can explain what needs to be considered for selects not to require columns. 

Best regards!

**Comment by olirice** [comment]
This was an intentional design decision to make all column grants explicit + declarative

In postgres permissions are procedural ( you could e.g. grant a whole table and then revoke a few columns and order of execution matters)

A single entity to express table + column grants solves that issue. I can see how that could be irritating if you're always granting every column but imo its the most flexible and consistent

going to close this issue but feel free to follow up to discuss

**Comment by Brax94** [comment]
Thank you for replying! 

In what case would adding an option for explicitly granting access to entire table without defining columns cause a problem?

Since i am implementing alembic-utils in an existing project, where production has users with privileges not defined using PGGrantTable,  i could create create code to fetch all columns of each of the tables i want to grant a user access to, or manually crafting each grant. Meanwhile, what i actually want to do is to simply say "grant this user access to this list of tables". For instance, for a read-only user with access to 20+ tables, the explicit way is very verbose.

**Comment by olirice** [comment]
> could not grant access to tables without defining the columns

did you try

```python
from alembic_utils.pg_grant_table import PGGrantTable

grant = PGGrantTable(
    schema="public",
    table="account",
    role="anon_user",
    grant='SELECT',
    with_grant_option=False,
)
```
?

I don't recall implementing it but its [all there](https://github.com/olirice/alembic_utils/blob/2e9ddacf2488220daf3697c0c7f099e03ceb2565/src/alembic_utils/pg_grant_table.py#L177-L209) and [tested](https://github.com/olirice/alembic_utils/blob/master/src/test/test_pg_grant_table.py)

**Comment by olirice** [comment]
my mistake
`DELETE` does not allow columns to be specified, so that's why its possible in that case

**Comment by olirice** [comment]
It's definitely possible to expand support to include granting all columns but its not something I want to include at this point due to the complexity it would bring to the auto-diffing logic

Permissions are a bit different than other entities and I'm not confident I could cover all the edge cases correctly. Given how critical permissions are I'm hesitant to risk it

**Comment by Brax94** [comment]
I understand, i have not really read the auto-diff logic yet, so i can't really say what is needed to support this. But could i suggest adding a test that breaks if no columns are defined, other than the raise check? That could at the very least help visualize the issues and allow potential contributors understand the problem better.

**Comment by olirice** [comment]
> adding a test that breaks if no columns are defined, other than the raise check

I didn't follow this, could you please expand on that?

**Comment by Brax94** [comment]
Of course, and thank you for indulging me! 

Right now, the functionallity for supplying None in the column field is kind of walled of with this bit of code

`       if PGGrantTableChoice(self.grant) in {C.SELECT, C.INSERT, C.UPDATE, C.REFERENCES}:
            if len(self.columns) == 0:
                raise BadInputException(
                    f"When grant type is {self.grant} a value must be provided for columns"
                )
`
This code offers no explanation or reason for not allowing None when grant is SELECT, INSERT etc. 

Furthermore, when i rewrite this code to allow None, all tests pass except [this](https://github.com/olirice/alembic_utils/blob/2e9ddacf2488220daf3697c0c7f099e03ceb2565/src/test/test_pg_grant_table.py#L44C1-L62C10), which again offers no further explanation of why we cannot have no columns specified. 

After looking a bit more at the test setup, i see that adding a test as i tried to explain earlier is not very straight forward. My preference would be to make the current tests parametrized, with the TEST_GRANT object as the parameter. 
Different TEST_GRANT objects would give different expected content of the migration_contents object, or in the case of an empty column field, expect an exception. 

That way, when someone wants to change the code, it will be instantly clear that they need to provide the proper expected migration content for this case if they want to create a PR. This would also increase test coverage for the different grant choices. 

But, simply adding some more explanation in the current test and documentation would also be okay 😄
