### ISSUE TITLE
AttributeError: module 'alembic.op' has no attribute 'create_function'

### ISSUE THREAD

**Issue by sonhoangnz** [olirice/alembic_utils#15]
Hello

It seems that the docs is a little out of date for https://olirice.github.io/alembic_utils/examples/

I have this:

def upgrade():
    public_to_upper_6fa0de = PGFunction(
            schema="public",
            signature="to_upper(some_text text)",
            definition="""
            returns text
            as
            $$ select upper(some_text) $$ language SQL;
            """
    )

  op.create_function(public_to_upper_6fa0de)

then got this:

AttributeError: module 'alembic.op' has no attribute 'create_function'

It should be: 

op.replace_entity(public_to_upper_6fa0de)

Note: my alembic version is 1.4.3

**Comment by olirice** [comment]
Thank you for opening the issue

I have updated the documentation to reflect the correct op names `op.[create|replace|drop]_entity`

**Comment by sonhoangnz** [comment]
Thanks, it is very fast help
