### ISSUE TITLE
Documentation mentions non-existing `from_path()` methods

### ISSUE THREAD

**Issue by EBoisseauSierra** [olirice/alembic_utils#17]
[The documentation](https://github.com/olirice/alembic_utils/commit/9fd8bb469b1943efc790288332a81250df58839a#diff-9eddf4dc51bf6a0125ca7fb094468ad284112270385c41cebce4f8f0a29620abR18) refers to `from_path()` methods for both `alembic_utils.pg_function.PGFunction` and `alembic_utils.pg_function.PGView`… yet these methods [don't seem](https://github.com/olirice/alembic_utils/blob/master/src/alembic_utils/pg_view.py#L12-L102) to be defined any more.

They are a great idea, though — we've reimplemented them on our side — but leaving them makes [the docs](https://olirice.github.io/alembic_utils/api/) a bit misleading.

**Comment by olirice** [comment]
That method is inherited from ReplacableEntity

https://github.com/olirice/alembic_utils/blob/56e3dce02736b29639de8fb9284e2df3ca7f09a1/src/alembic_utils/replaceable_entity.py#L65

Could you please provide the alemic_utils version you’re on and more info on how you’re trying to access the method?

**Comment by EBoisseauSierra** [comment]
Oh, I stand corrected — I guess I've just been a bit stupid here actually and hadn't investigated the superclass.

```python
PGMaterializedView.from_path(<pathlib.Path>)
```
where the file pointed toward to is of the form
```sql
CREATE MATERIALIZED VIEW <schema>.<view_name> AS
SELECT
    <…>
;
```
works like a charm indeed!
(Sorry for the fuss, but thanks for your work!)
