### ISSUE TITLE
Remove psycopg2-binary dependency

### ISSUE THREAD

**Issue by tl24** [olirice/alembic_utils#45]
Recently we added alembic_utils to our application.  When I did so I started getting errors in our AWS lambda environment with psycopg2.  I believe this stems from alembic_utils dependency on psycopg2-binary.  I believe the order of installation of psycopg2 and psycopg2-binary matters in this case.  From the psycopg2 docs, python packages should not have a dependency on psycopg2-binary. From https://www.psycopg.org/docs/install.html: "If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency"

Can you remove the psycopg2-binary from install-requires, and possibly move it to DEV_REQUIRES?  From the looks of the source code, psycopg2 is never imported so its not a direct dependency.  Alembic does not list psycopg2 or psycopg2-binary as a dependency either.

**Comment by olirice** [comment]
Thanks for the references. I’m currently OOO but will cut a new release without psycopg2 as a dependency NLT Tuesday

**Comment by olirice** [comment]
Resolved by 1e76215f82993f531ca3306cf5a2b1f0dfdb6642
Its available on pypi as `alembic_utils==0.5.6`
