### ISSUE TITLE
Creating auto migration slow for PGMaterializedView with data

### ISSUE THREAD

**Issue by tdamsma** [olirice/alembic_utils#55]
I am creating a bunch of materialized views (and left the defaul `with_data=True`) and it was really slow (many minutes). On inspection, it seemed alembic was waiting for the database. 

Of course the point of these materialized views is to speed up certain access patterns and the queries are quite slow, that's why I am materilizing them.

Now I want the migration to create views with data, but it seems like that is causing the automigrate creation to also run with date. After setting `with_data=False` they automigration is generated in a few seconds.

I suspect that during automigration the query is somehow run against the datse, perhaps to check for errors? Would it make sense to temporarily have `with_data=False` during auto migration generation?

**Comment by olirice** [comment]
good call
resolved with 37abb942e327281eaafc8c4502d670ea6f46cff3

that update is available in version 0.7.1 on pypi
