### ISSUE TITLE
PGGrantTable.from_database requires `grantor = CURRENT_USER`

### ISSUE THREAD

**Issue by Gracecr** [olirice/alembic_utils#78]
https://github.com/olirice/alembic_utils/blob/76607483cb9f3d8de9fb1aba4c0409c513da3668/src/alembic_utils/pg_grant_table.py#L151

More a question than an issue. I'm guessing there's good reason for it.

While creating the grant tables for my database, I ran into some trouble as some of my tables had different owners. I was able to resolve this by making them all owned by my migration user. I assume that is what this line in the documentation is explaining:

> PGGrantTable requires the role name being used to generate migrations to match the role name that executes migrations.

Why is this constraint necessary?

**Comment by olirice** [comment]
The main thing it does is enables uniquely identifying the records in `information_schema.role_column_grants` which is needed for reflection and diffing

it also avoids avoids runtime (migration time) permissions errors b/c we've checked that the migration role is able to perform the grant
