### ISSUE TITLE
Colon character escaped unnecessarily in view autogeneration

### ISSUE THREAD

**Issue by johnwiseheart** [olirice/alembic_utils#95]
Similar to the example in #58, My view looks something like this
```
query = "SELECT concat('https://something/', column) FROM table"
some_view = PGMaterializedView(schema="public", signature="example", definition=query)
```
Which generated a revision something like so
```
public_something = PGMaterializedView(
    schema="public",
    signature="something",
    definition="SELECT concat('https\\://something/', column) FROM table",
)
op.replace_entity(public_something)
```

I'd expect that the `:` character should not be escaped in the definition, or at least there should be a way to un-escape it. 

Seemingly, the way it is right now, there is not a way to auto-generate a view containing a URL without manual changes.

**Comment by olirice** [comment]
I was not able to reproduce that result. Are you on the latest version of alembic_utils?


<img width="831" alt="Screen Shot 2022-07-01 at 2 52 34 PM" src="https://user-images.githubusercontent.com/12958657/176960613-eb3411ba-8d3d-4e4d-970f-589ee8a0095c.png">

**Comment by johnwiseheart** [comment]
Ah my mistake, I missed a change in the example, which is that this is a Materialized view. I just checked locally and with the latest version, the issue seems to only appear for the materialized view, and not the regular view. Does that make sense? 

I updated the example to reflect the change
